#!/usr/bin/python

import utils
import sys

if __name__ == "__main__":
   filename = sys.argv[1]
   
   dataframe = utils.read_dataframe(filename)
   
   for value in dataframe.values:
      print value[0], value[1], value[2]
